name: Deploy on Staging Merge/Push
'on':
  push:
    branches:
      - staging
    paths:
    - "src/**"
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - name: Deploy to Firebase Staging URL
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDPONICS_A0403 }}'
          channelId: staging
          projectId: cloudponics-a0403