name: Preview Deploy on PR

on:
  pull_request:
    paths:
    - "src/**"
    # branches-ignore:
    # - "master"
    # - "staging"
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - name: Deploy to Firebase Preview URL
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDPONICS_A0403 }}'
          expires: 7d
          projectId: cloudponics-a0403